In [42]:
from math import *
import numpy as np

# Questão 1
Implementar a ordenação de arrays pelo método do [Bubble Sort](https://pt.wikipedia.org/wiki/Bubble_sort).

In [39]:
def BubbleSort(lista):
    i=0
    while i<=len(lista)-2: #usamos len(lista)-2, para ele não comparar o elemento n com o n+1(que não existe)
        if lista[i]>lista[i+1]: #se fizermos len(lista)-1, quando chegar em i=len(lista)-1, ele irá comparar com o elemento na posição i=len(lista), que não existe
            x=lista[i]
            lista[i]=lista[i+1]
            lista[i+1]=x
        i=i+1
    i=0 #volta para a posição 0  
    while i<=len(lista)-2:
        if lista[i]>lista[i+1]:
            BubbleSort(lista) #recursão, pois no primeiro while só percorremos a lista uma única vez
        i=i+1
    return lista

In [40]:
BubbleSort([1,0,7,3,4,5,4,7])

[0, 1, 3, 4, 4, 5, 7, 7]

# Questão 2
Somar duas matrizes, por meio de uma soma dos elementos correspondentes (soma elemento a elemento). Ou seja, sejam $A$ e $B$ as matrizes que serão somadas, cada elemento da matriz resultante $C$ será dado por:

$$c_{ij}= a_{ij} + b_{ij}$$

In [111]:
def somamat(x,y):
    if x.shape!=y.shape:
        print('Coloque matrizes com dimensões iguais')    
    else:
        i=0
        j=0
        c=np.matrix(np.zeros(x.shape))
        while i<x.shape[0]: #x.shape[0] me devolve a quantidade de linhas da matriz
            j=0 #precisamos voltar para a coluna 0 para fazermos a soma dos elementos das linhas i>1
            while j<x.shape[1]: #x.shape[1] me devolve a quantidade de colunas da matriz
                c[i,j]=x[i,j]+y[i,j]
                j=j+1
            i=i+1
    return c

In [112]:
x=np.matrix([[1,2,3],[4,5,6],[7,8,9]])
y=x*2
x.shape

(3, 3)

In [115]:
somamat(x,y)

matrix([[ 3.,  6.,  9.],
        [12., 15., 18.],
        [21., 24., 27.]])

# Questão 3
Criar uma função que recebe uma matriz como parâmetro de entrada e troca 2 linhas escolhidas (parâmetros de entrada) de posição. 

In [123]:
def trocalinhas(matriz,l1,l2):
    j=0
    while j<matriz.shape[1]:
        x=matriz[l1,j]
        matriz[l1,j]=matriz[l2,j]
        matriz[l2,j]=x
        j=j+1
    return matriz

In [124]:
x=np.matrix([[1,2,3],[4,5,6],[7,8,9]])
x

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [125]:
trocalinhas(x,0,1)

matrix([[4, 5, 6],
        [1, 2, 3],
        [7, 8, 9]])

In [126]:
tr=np.matrix([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16],[17,18,19,20]])
tr

matrix([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16],
        [17, 18, 19, 20]])

In [128]:
trocalinhas(tr,3,4)

matrix([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16],
        [17, 18, 19, 20]])

# Questão 4
Criar uma função que recebe uma matriz como parâmetro de entrada e inverte a ordem das linhas dessa matriz. 

In [131]:
def invertelinhas(matriz):
    nlin=matriz.shape[0]
    ncol=matriz.shape[1]
    i=0
    j=0
    while i<nlin//2:
        j=0
        while j<ncol:
            x=matriz[i,j]
            matriz[i,j]=matriz[nlin-1-i,j]
            matriz[nlin-1-i,j]=x
            j=j+1
        i=i+1
    return matriz

In [132]:
invertelinhas(tr)

matrix([[ 1,  2,  3,  4],
        [13, 14, 15, 16],
        [ 9, 10, 11, 12],
        [ 5,  6,  7,  8],
        [17, 18, 19, 20]])