# Aula 18

## Funções

* np.dot(a,b) ou a.dot(b) = multiplicação das matrizes
* np.matrix(a) = transforma o array em matriz
* A.T = transposição
* np.random.random(x,y)
    * (x,y) intervalo aberto em y
* a.mean() = média
* a.sum() = soma
* a.cumsum() = soma acumulada 
    - (axis=0) = coluna
    - (axis=1) = linha

## NumPy (continuação)

### Tipo Array *versus* Tipo Matriz

Na aula passada, definimos matrizes como um array (**ndarray**) de duas dimensões. Mas existe no NumPy, um tipo **matrix** para trabalharmos diretamente com matrizes. Apesar de representarem a mesma coisa, são de tipos diferentes e portanto, algumas operações aplicadas sobre elas apresentam resultados diferentes. 

In [1]:
import numpy as np

In [3]:
a = np.array([[1,2],[3,4]])
b = np.array([[1,9],[7,5]])

In [4]:
a

array([[1, 2],
       [3, 4]])

In [14]:
b

array([[1, 9],
       [7, 5]])

In [16]:
a*b #faz a multiplicação de elemento por elemento (aij*bij)

array([[ 1, 18],
       [21, 20]])

In [17]:
np.dot(a,b) #faz a multiplicação das matrizes

array([[15, 19],
       [31, 47]])

In [19]:
a.dot(b) #mesma coisa

array([[15, 19],
       [31, 47]])

In [20]:
A = np.matrix(a)
B = np.matrix(b)

In [22]:
A

matrix([[1, 2],
        [3, 4]])

In [23]:
B

matrix([[1, 9],
        [7, 5]])

In [24]:
#Quando transformarmos em matriz, a multplicação se torna uma multiplicação de matrizes
A*B

matrix([[15, 19],
        [31, 47]])

In [25]:
#Não é mais necessário a utilização da função np.dot(A,B)
A.dot(B)

matrix([[15, 19],
        [31, 47]])

In [26]:
print(type(A))
print(type(a))
print(type(A*B))
print(type(a*b))

<class 'numpy.matrix'>
<class 'numpy.ndarray'>
<class 'numpy.matrix'>
<class 'numpy.ndarray'>


* A Transposição de vetores do tipo **array** (unidimensionais) deve ser feita usando `.reshape()`. Matrizes do tipo array realizam a transpoição usando o método `.T`. Para o tipo **matrix**, o método `.T` realiza ambas transposições.

In [28]:
A.T #transposição -> o que é linha vira coluna

matrix([[1, 3],
        [2, 4]])

In [46]:
c=np.ones(4)
print(c.shape)
c

(4,)


array([1., 1., 1., 1.])

In [47]:
print(c.T.shape)
c.T

(4,)


array([1., 1., 1., 1.])

In [49]:
print(c.reshape(4,1).shape)
c.reshape(4,1)

(4, 1)


array([[1.],
       [1.],
       [1.],
       [1.]])

In [51]:
C = np.matrix(c)
print(C)
print(C.shape)
print(C.T.shape)
C.T

[[1. 1. 1. 1.]]
(1, 4)
(4, 1)


matrix([[1.],
        [1.],
        [1.],
        [1.]])

In [57]:
d=np.array([np.ones(4)])
#é diferente de fazer d=np.array(np.ones(4))
#quando fazemos d=np.array(np.ones(4)), colocamos 4 elementos em 4 posições
#quando fazemos d=np.array([np.ones(4)]), colocamos 4 elementos dentro de um 1 vetor na posição 0
d

array([[1., 1., 1., 1.]])

In [56]:
d.T

array([[1.],
       [1.],
       [1.],
       [1.]])

In [61]:
d[0]

array([1., 1., 1., 1.])

In [62]:
e=np.array(np.ones(4))
e

array([1., 1., 1., 1.])

In [64]:
e[0]

1.0

### Criando Matrizes

Podemos criar uma matriz a partir de todas as técnicas apresentadas na aula anterior para matriz do tipo array de 2 dimensões. 

Os vetores criados a partir do tipo **ndarray** são unidimensionais. No entanto, os vetores criados a partir da função `np.matrix()` gera um tipo **matrix** bidimensional.  Vamos ver isso?

In [69]:
M = np.matrix(np.ones((3,3)))
M

matrix([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [76]:
L = np.matrix(np.ones(3)*10) #vetor linha
L

matrix([[10., 10., 10.]])

In [71]:
C = np.matrix(np.arange(1,4))
C

matrix([[1, 2, 3]])

In [72]:
C.T #vetor coluna

matrix([[1],
        [2],
        [3]])

In [77]:
print(L.ndim)
L.shape

2


(1, 3)

In [78]:
f=np.matrix(np.ones(3))
f

matrix([[1., 1., 1.]])

In [79]:
f.shape

(1, 3)

In [80]:
f.ndim

2

In [81]:
g=np.ones(3)
g

array([1., 1., 1.])

In [82]:
g.shape

(3,)

In [83]:
g.ndim

1

### Indexação Booleana

In [84]:
nomes = np.array(['Ana','Carol','David','Walter'])
nomes

array(['Ana', 'Carol', 'David', 'Walter'], dtype='<U6')

In [91]:
nomes = 'Carol'

In [93]:
dados = np.random.random((4,5))
dados

array([[0.79899568, 0.03277297, 0.51501969, 0.83618543, 0.86401385],
       [0.2576017 , 0.87136576, 0.22576766, 0.00596509, 0.50053625],
       [0.19931082, 0.05034313, 0.51187379, 0.59548409, 0.44184559],
       [0.8535448 , 0.17428008, 0.10487188, 0.02894442, 0.78712197]])

In [94]:
dados[nomes == 'Carol',:]

array([[[0.79899568, 0.03277297, 0.51501969, 0.83618543, 0.86401385],
        [0.2576017 , 0.87136576, 0.22576766, 0.00596509, 0.50053625],
        [0.19931082, 0.05034313, 0.51187379, 0.59548409, 0.44184559],
        [0.8535448 , 0.17428008, 0.10487188, 0.02894442, 0.78712197]]])

In [95]:
nomes = np.array(['Ana', 'Carol', 'Walter', 'Carol', 'Ana', 'Hugo', 'Hugo'])
nomes

array(['Ana', 'Carol', 'Walter', 'Carol', 'Ana', 'Hugo', 'Hugo'],
      dtype='<U6')

In [96]:
set(nomes)

{'Ana', 'Carol', 'Hugo', 'Walter'}

In [97]:
sorted(nomes)

['Ana', 'Ana', 'Carol', 'Carol', 'Hugo', 'Hugo', 'Walter']

In [101]:
m = np.matrix(np.random.randint(1,11,(4,4)))
m

matrix([[ 9,  8,  3,  7],
        [ 6,  6, 10,  8],
        [ 9,  5, 10,  8],
        [ 4,  7,  8,  6]])

In [102]:
m.mean()

7.125

In [108]:
m.mean(axis=0)
#média das linhas de cada coluna

matrix([[7.  , 6.5 , 7.75, 7.25]])

In [106]:
m.mean(axis=1)
#média das colunas de cada linha

matrix([[6.75],
        [7.5 ],
        [8.  ],
        [6.25]])

In [112]:
m.sum(axis=0)
#soma das linhas de cada coluna
#soma das colunas

matrix([[28, 26, 31, 29]])

In [110]:
m.sum(axis=1)
#soma das colunas de cada linha

matrix([[27],
        [30],
        [32],
        [25]])

In [113]:
m.cumsum(axis=0)
#soma acumulada das colunas

matrix([[ 9,  8,  3,  7],
        [15, 14, 13, 15],
        [24, 19, 23, 23],
        [28, 26, 31, 29]], dtype=int32)

In [114]:
m.cumsum(axis=1)
#soma acumulada das linhas

matrix([[ 9, 17, 20, 27],
        [ 6, 12, 22, 30],
        [ 9, 14, 24, 32],
        [ 4, 11, 19, 25]], dtype=int32)