# Aula 17

In [7]:
import numpy as np
#!pip install numpy

In [8]:
minha_lista = [1,2,3,4,5]

In [10]:
meu_array = np.array(minha_lista)
meu_array

array([1, 2, 3, 4, 5])

In [11]:
type(minha_lista)

list

In [12]:
type(meu_array)

numpy.ndarray

In [13]:
minha_lista*2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [14]:
meu_array*2

array([ 2,  4,  6,  8, 10])

In [15]:
arr1 = np.array([1,1.5,2,2.5])
arr1

array([1. , 1.5, 2. , 2.5])

In [16]:
arr2 = np.array([[1,2,3,4], [4,6,7]])
arr2

array([list([1, 2, 3, 4]), list([4, 6, 7])], dtype=object)

In [17]:
arr3 = np.array([[1,2,3,4], [4,6,7,8]])
arr3

array([[1, 2, 3, 4],
       [4, 6, 7, 8]])

In [18]:
arr2.ndim

1

In [23]:
arr3.ndim
#dimensão

2

In [22]:
arr3.shape
#linhas e colunas

(2, 4)

In [30]:
arr3[0,0]
#matriz[linha,coluna]=retorna o elemento
#linha1=linha0

1

In [28]:
arr3[1,1]

6

In [31]:
arr3[0,2]

3

In [32]:
np.array(['1','1.5','2','2.5']).astype(float)

array([1. , 1.5, 2. , 2.5])

In [34]:
np.array([1,1.5,2,2.5]).astype(int)

array([1, 1, 2, 2])

In [35]:
z = np.zeros(10)
z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [36]:
z[1]=10
z

array([ 0., 10.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [37]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [44]:
np.ones([3,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [48]:
np.ones([2,3,2])
#(numero de matrizes,linhas,colunas)

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [51]:
np.empty((3,2))

array([[2.42092166e-322, 1.03977794e-312],
       [1.12465777e-312, 2.47032823e-322],
       [1.06099790e-312, 1.12465777e-312]])

In [53]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [59]:
np.arange(3,21)

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
       20])

In [57]:
np.arange(1,10,.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])

In [61]:
np.linspace(1,10,30)
#vai de 1 a 10 e divide em 30 números

array([ 1.        ,  1.31034483,  1.62068966,  1.93103448,  2.24137931,
        2.55172414,  2.86206897,  3.17241379,  3.48275862,  3.79310345,
        4.10344828,  4.4137931 ,  4.72413793,  5.03448276,  5.34482759,
        5.65517241,  5.96551724,  6.27586207,  6.5862069 ,  6.89655172,
        7.20689655,  7.51724138,  7.82758621,  8.13793103,  8.44827586,
        8.75862069,  9.06896552,  9.37931034,  9.68965517, 10.        ])

In [64]:
np.random.random(5)

array([0.17855858, 0.81302824, 0.82802711, 0.15904457, 0.46238037])

In [66]:
np.random.randint(1,11,(2,3))
#(intervalo de números aleatórios,(linhas,colunas))

array([[ 8,  2,  3],
       [ 7, 10,  9]])

In [68]:
np.eye(3)
#matriz identidade

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [69]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [71]:
np.eye(3,4,1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [77]:
np.eye(3,4,1)
#(-,-,controla a posição da diagonal principal)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [81]:
a=np.arange(1,101)
a

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [82]:
b=a.reshape(4,25)
b

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
         14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25],
       [ 26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
         39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,
         64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75],
       [ 76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,
         89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [83]:
np.arange(10).reshape(10,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [88]:
c = np.arange(10)
n = c.shape
n

(10,)

In [90]:
c.reshape(n[0],1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [91]:
arr = np.array([[1,2,3], [4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [92]:
arr*arr

array([[ 1,  4,  9],
       [16, 25, 36]])

In [93]:
arr*2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [95]:
arr2=np.array([[0,4,1], [7,2,12]])
arr2

array([[ 0,  4,  1],
       [ 7,  2, 12]])

In [97]:
arr2>arr

array([[False,  True, False],
       [ True, False,  True]])

In [98]:
arr3 = np.arange(1,11)
arr3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [101]:
arr[arr2>arr]

array([2, 4, 6])

In [102]:
arr2[arr2>arr]

array([ 4,  7, 12])

In [100]:
arr-arr

array([[0, 0, 0],
       [0, 0, 0]])

In [103]:
arr_fatia = arr3[5:8]
print(arr_fatia)
arr_fatia[:] = -1
arr_fatia

[6 7 8]


array([-1, -1, -1])

In [ ]:
bfmk