# Aula 17

## Funções

* np.array()
* .dim = retorna quantas linhas (vetores em linha) temos
* .shape = retorna quantas linhas e colunas temos
* .dtype = tipo dos elementos (str, float, bool, int,...)
* .astype(float); .astype(str); .astype(int)
* np.zeros(x); np.ones(x); np.empty(x) = cria arrays de x 0s ou 1s
    - np.zeros(shape=(x,y), dtype, order) ou np.zeros((x,y,z), dtype, order)
        - **Caso 2**
        * x = quantidade de matrizes
        * y = quantidade de linhas
        * z = quantidade de colunas
* np.arange (início, fim, passo) = criar array
    - Aberto na fronteira direita 
* np.linspace (início, fim, número de pontos) = Cria uma sequência de números uniformemente espaçados entre os limites dado
* np.identity(n) = cria a matriz identidade nxn
* np.eye(linha,coluna) = matriz de unidades
* .reshape(matrizes,linha,coluna) = modificar as dimensões do array criado
* .copy()

In [1]:
!pip install numpy

In [3]:
import numpy as np
from math import *
from random import *

## NumPy: Numerical Python

Permite trabalhar com vetores e matrizes de $N$ dimensões, de uma forma comparável e com uma sintaxe semelhante ao Matlab. É uma poderosa biblioteca do Python que fornece um grande conjunto de funções e operações que ajudam na realização de cálculos numéricos. Esses tipos de cálculos numéricos são amplamente utilizados em tarefas como:

* **Modelos de Machine Learning:** os arrays NumPy são usados para armazenar os dados de treinamento, bem como os parâmetros dos modelos de Machine Learning.

* **Processamento de Imagem e Computação Gráfica**: imagens no computador são representadas como arrays multidimensionais de números. O NumPy fornece algumas excelentes funções de biblioteca para rápida manipulação de imagens. Alguns exemplos são o espelhamento de uma imagem, a rotação de uma imagem por um determinado ângulo etc.

* **Tarefas matemáticas**: é bastante útil para executar várias tarefas matemáticas como integração numérica, diferenciação, interpolação e muitas outras. O NumPy possui também funções incorporadas para álgebra linear e geração de números aleatórios. 

<img src="../Figuras/python_matlab.png" alt="drawing" width="500"/>

*Fonte*: https://medium.com/ensina-ai/entendendo-a-biblioteca-numpy-4858fde63355

In [6]:
minha_lista=[1,2,3,4,5]
print('Array Python (Listas):',minha_lista,'-> Tipo:',type(minha_lista))
print()
meu_array=np.array(minha_lista)
print('Array NumPy:',meu_array,'-> Tipo:',type(meu_array))

Array Python (Listas): [1, 2, 3, 4, 5] -> Tipo: <class 'list'>

Array NumPy: [1 2 3 4 5] -> Tipo: <class 'numpy.ndarray'>


Um **array NumPy** é uma extensão de um **array Python** (listas), que lida apenas com arrays unidimensionais.

In [9]:
minha_lista*2 #faz uma concatenação

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [10]:
meu_array*2 #multiplica por 2

array([ 2,  4,  6,  8, 10])

O **ndarray**, um objeto fundamental do NumPy, é uma matriz $n$-dimensional, isso significa que ele contém uma **coleção de elementos do mesmo tipo** (dados homogêneos) indexados usando $n$ números inteiros (dimensão da matriz).

Todo array possui uma forma (`shape`), uma tupla indicando o tamanho de cada dimensão e um `dtype`, um objeto que descreve o tipo de dados da matriz. 

- `shape` = mostrando quantas linha e colunas temos para exemplificar -> (nº linhas, nº colunas) ou (nº linhas, ) = (n linhas, 1 coluna) = vetor coluna
- `dtype` = pode ser: bool, int, float

## Tipo Array

### Criando ndarrays

In [11]:
dados1 = [1,1.5,2,2.5]
arr1=np.array(dados1)
print(arr1)
arr1

[1.  1.5 2.  2.5]


array([1. , 1.5, 2. , 2.5])

Sequências aninhadas, como uma lista de listas de igual comprimento, serão convertidas em uma matriz multidimensional:

In [134]:
dados2 = [[1,2,3,4]] #listas
dados2.append([5,6,7,8])
dados2

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [135]:
arr2 = np.array(dados2) #numpy
print(arr2)
arr2

[[1 2 3 4]
 [5 6 7 8]]


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

Sublistas de tamanhos diferentes não são convertidas em uma matriz

In [15]:
dados3 = [[1,2,3,4]]
dados3.insert(1,[5,6,7])
dados3

[[1, 2, 3, 4], [5, 6, 7]]

In [16]:
arr3=np.array(dados3)
print(arr3)
arr3

[list([1, 2, 3, 4]) list([5, 6, 7])]


array([list([1, 2, 3, 4]), list([5, 6, 7])], dtype=object)

In [17]:
print('Dimensão de arr1:', arr1.ndim)
print('Shape de arr1:', arr1.shape)
print()
print('Dimensão de arr2:', arr2.ndim)
print('Shape de arr2:', arr2.shape)
print()
print('Dimensão de arr3:', arr3.ndim)
print('Shape de arr3:', arr3.shape)
print()

Dimensão de arr1: 1
Shape de arr1: (4,)

Dimensão de arr2: 2
Shape de arr2: (2, 4)

Dimensão de arr3: 1
Shape de arr3: (2,)



No caso acima:
- *dimensão de arr1 = 1, pois tem apenas um vetor (linha) e seu shape é (4,), pois possui 1 linha e 4 colunas*
- *dimensão de arr2 = 2, pois tem dois vetores (linhas) e seu shape é (2,4), pois possui 2 linhas e 4 colunas*

In [20]:
shape2 = arr2.shape
print('O arr2 possui',shape2[0],'linhas e',shape2[1],'colunas.')

O arr2 possui 2 linhas e 4 colunas.


In [30]:
print('Tipo de dados do arr1:',arr1.dtype)
print('Tipo de dados do arr2:',arr2.dtype)

Tipo de dados do arr1: float64
Tipo de dados do arr2: int32


Se você tiver um array de strings representando números, poderá usar `astyp(float)` para converter os dados para a forma numérica:

In [32]:
x=np.array(['1','2','3','4','5'])
y=x.astype(float)
print(x)
print()
y

['1' '2' '3' '4' '5']



array([1., 2., 3., 4., 5.])

In [35]:
x=np.array(['1','2','3','4','5'])
y=x.astype(int)
print(x)
print()
y

['1' '2' '3' '4' '5']



array([1, 2, 3, 4, 5])

In [68]:
np.zeros(10) 

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [70]:
np.zeros((4,3,3),int)
#4 matrizes, 3 linhas, 3 colunas

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]])

In [67]:
np.ones((5,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [55]:
np.empty((1,6))

array([[0., 0., 0., 0., 0., 0.]])

In [71]:
np.array([1,2,3],float)

array([1., 2., 3.])

In [74]:
np.arange(30) #aberto na fronteira direita

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [77]:
np.arange(1,21,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [80]:
np.arange(1,21,2,float)

array([ 1.,  3.,  5.,  7.,  9., 11., 13., 15., 17., 19.])

In [86]:
np.arange(0.1,0.5,0.01)

array([0.1 , 0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ,
       0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31,
       0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42,
       0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49])

In [88]:
np.linspace(1,10,15)

array([ 1.        ,  1.64285714,  2.28571429,  2.92857143,  3.57142857,
        4.21428571,  4.85714286,  5.5       ,  6.14285714,  6.78571429,
        7.42857143,  8.07142857,  8.71428571,  9.35714286, 10.        ])

In [98]:
np.eye(3,3,0)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [107]:
np.eye(3,3,-1)
# matriz 3x3 com a diagonal de unidades abaixo da diagonal principal

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [108]:
np.eye(3,3,1)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [122]:
x=np.arange(12,0,-1)
x

array([12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [129]:
b=x.reshape(4,3)
b

array([[12, 11, 10],
       [ 9,  8,  7],
       [ 6,  5,  4],
       [ 3,  2,  1]])

In [132]:
c=b.reshape(4,1,3) #4 matrizes de 1 linha e 3 colunas
c

array([[[12, 11, 10]],

       [[ 9,  8,  7]],

       [[ 6,  5,  4]],

       [[ 3,  2,  1]]])

## Operações Aritméticas

Qualquer operação aritmética entre arrays de tamanho igual aplica a operação elemento a elemento.

In [133]:
arr = np.array([[1,2,3], [4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [137]:
arr*arr #igual a arr**2

array([[ 1,  4,  9],
       [16, 25, 36]])

In [141]:
x=arr**2
b=x.astype(float)
b

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [142]:
arr-arr

array([[0, 0, 0],
       [0, 0, 0]])

In [143]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [146]:
arr2 = np.array([[0,4,1],[7,2,12]])
arr2

array([[ 0,  4,  1],
       [ 7,  2, 12]])

In [147]:
arr2>arr

array([[False,  True, False],
       [ True, False,  True]])

In [148]:
arr3 = np.arange(10,40,10)
arr3

array([10, 20, 30])

In [149]:
arr*arr3

array([[ 10,  40,  90],
       [ 40, 100, 180]])

In [153]:
arr4=np.arange(1,13,1)
arr4

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [154]:
teyla=arr4.reshape(4,3)
teyla

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [156]:
teyla2=arr4.reshape(3,4)
teyla2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [158]:
teyla*teyla2

ValueError: operands could not be broadcast together with shapes (4,3) (3,4) 

## Indexação Simples e "Fatiamento"

Os itens de um array podem ser acessados e atribuídos da mesma forma que outras sequências do Python, como listas por exemplo.

Semelhante às listas, arrays também podem ser "fatiados". Como os arrays podem ser multidimensionais, você deve especificar uma "fatia" para cada dimensão do array. 

In [160]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [162]:
arr[5]

6

In [163]:
arr[5:8]

array([6, 7, 8])

In [165]:
arr[5:8] = 12
arr

array([ 1,  2,  3,  4,  5, 12, 12, 12,  9, 10])

Diferentemente do que ocorre com as listas, as "fatias" dos arrays são visualizações da matriz original. Isso significa que os dados não são copiados e quaisquer modificações dessas "fatias" serão refletidas no array de origem.

In [166]:
arr_fatia = arr[5:8]
arr_fatia

array([12, 12, 12])

In [167]:
arr_fatia[1] = 1234
arr_fatia

array([  12, 1234,   12])

In [168]:
arr

array([   1,    2,    3,    4,    5,   12, 1234,   12,    9,   10])

In [177]:
arr_fatia = arr[5:8]
arr_fatia

array([  12, 1234,   12])

In [179]:
arr_fatia[:] = 0 
arr

array([ 1,  2,  3,  4,  5,  0,  0,  0,  9, 10])

In [180]:
arr_copia = arr[:].copy()
arr_copia

array([ 1,  2,  3,  4,  5,  0,  0,  0,  9, 10])

In [181]:
arr_fatia = arr_copia[5:8]
arr_fatia

array([0, 0, 0])

In [182]:
arr_fatia[:] = [12,12,13]
arr

array([ 1,  2,  3,  4,  5,  0,  0,  0,  9, 10])

In [183]:
arr_copia

array([ 1,  2,  3,  4,  5, 12, 12, 13,  9, 10])

In [186]:
arr2d = np.arange(1,10)
arr2d

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [187]:
arr2d = arr2d.reshape(3,3)
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [188]:
arr2d[2]

array([7, 8, 9])

In [189]:
#Podemos acessar um elemento aij da matriz A de duas formas:
print(arr2d[0][2]) # a[i][j]
print(arr2d[0, 2]) #a[i,j]

3
3


In [191]:
arr2d[0,2] + arr2d[1,1]

8

In [193]:
arr2d[:2] #seleciona as duas primeiras linhas

array([[1, 2, 3],
       [4, 5, 6]])

In [195]:
arr2d[:2,1:] #seleciona os elementos na primeira e segunda linha, que estão na segunda e terceira coluna

array([[2, 3],
       [5, 6]])

In [198]:
arr2d[:,:2] #seleciona todas as linhas até a 2ª coluna

array([[1, 2],
       [4, 5],
       [7, 8]])

In [199]:
arr2d[:,2] #seleciona todas as linhas da terceira coluna

array([3, 6, 9])

In [202]:
print(arr2d[2,:].shape)
arr2d[2,:]
# vetor coluna

(3,)


array([7, 8, 9])

In [203]:
print(arr2d[2:,:].shape)
arr2d[2:,:]
# vetor linha

(1, 3)


array([[7, 8, 9]])